name: Android Debug Build

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  build:
    name: Build Debug Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew  # Fixes "gradlew not found" error
        
      - name: Clean Gradle cache
        run: rm -rf ~/.gradle/caches/

      - name: Generate Debug Keys
        run: pwd; keytool -genkey -v -keystore debug.keystore -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US" ; ls -l

      - name: Build Release APK
        run: pwd; ls-l ; ./gradlew assembleDebug

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7
