name: Android CI

on:
  push:
    paths:
      - 'app/src/main/AndroidManifest.xml'
      - 'app/src/main/res/layout/activity_main.xml'
      - 'app/src/main/java/**'
  workflow_dispatch:  # Allows manual execution

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew  # Fixes "gradlew not found" error
        
      - name: Clean Gradle cache
        run: rm -rf ~/.gradle/caches/
        
      - name: Create Keystore
        run: echo "${{ secrets.ENCODED_PROD_KS }}" | base64 -d > prod.keystore
        
      - name: Build Release APK
        env: # Or as an environment variable
          PROD_KEYSTORE_PASSWORD: ${{ secrets.PROD_KEYSTORE_PASSWORD }}
          PROD_KEY_ALIAS: ${{ secrets.PROD_KEY_ALIAS }}
          PROD_KEY_PASSWORD: ${{ secrets.PROD_KEY_PASSWORD }}
        run: ./gradlew assembleRelease testReleaseUnitTest

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk
          retention-days: 7
